### ISSUE TITLE
psr要求, Message对象是一个不可变对象.

### ISSUE THREAD

**Issue by windqyoung** [easy-swoole/http#10]
https://github.com/easy-swoole/http/blob/1dd718dbc351f139467df905c3707534aebebfae/src/Message/Message.php#L44

如果要修改对象的属性, 应该重新实例化一个对象, 而不是直接修改原始对象的属性.

别的psr对象也应该是不可变对象.

**Comment by kiss291323003** [comment]
完全按照规范来的话、、、、、很浪费。
