### ISSUE TITLE
控制器处理能不能改成 下划线转驼峰 (首字母大写) 的处理方式

### ISSUE THREAD

**Issue by browningweb** [easy-swoole/http#11]
https://github.com/easy-swoole/http/blob/1dd718dbc351f139467df905c3707534aebebfae/src/Dispatcher.php#L153

由于之前在tp模式下，请求地址控制器为两个以上单词的都用下划线分割了，比如 HelloWorld/index 在 tp 模式下为 hello_world/index。

`\EasySwoole\Utility\Str::studly`

**Comment by kiss291323003** [comment]
psr4规范不允许
